# Generated by Django 5.2.8 on 2025-11-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('founder_name', models.CharField(max_length=100, verbose_name='Имя основателя')),
                ('founder_image', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Фото Основателя')),
                ('founder_image1', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Иконка1')),
                ('founder_image2', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Иконка2')),
                ('founder_image3', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Иконка3')),
                ('founder_image4', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Иконка4')),
                ('founder_image5', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Иконка5')),
                ('url_field', models.URLField(blank=True, null=True, verbose_name='Подробности')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_img', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Иконка')),
            ],
        ),
    ]
